spring:
  datasource:
    url: jdbc:mysql://localhost:3306/educational
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wen1106.
#  mvc:
#    static-path-pattern: /static/**
##
#  thymeleaf:
#    cache: false
#    prefix: classpath:/templates/
#    encoding: UTF-8
#    suffix: .html



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl